version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hrms_postgres
    restart: always
    environment:
      POSTGRES_DB: hrms
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database:/docker-entrypoint-initdb.d

volumes:
  pgdata:
