version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_pass
      POSTGRES_DB: hrms
    volumes:
      - hrms_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  hrms_data:
